-- 코드를 입력하세요
SELECT M.AUTHOR_ID,M.AUTHOR_NAME, M.CATEGORY, SUM(M.TOTAL_SALES) AS TOTAL_SALES_SUM
FROM (
    SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, (S.SALES * B.PRICE) AS TOTAL_SALES
    FROM BOOK B
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
) M
GROUP BY M.AUTHOR_ID, M.AUTHOR_NAME, M.CATEGORY
ORDER BY M.AUTHOR_ID ASC, M.CATEGORY DESC;
