-- 코드를 입력하세요
SELECT 
    TITLE,B.BOARD_ID,REPLY_ID,WRITER_ID,CONTENTS,TO_DATE(B.CREATED_DATE,'YYYY-MM-DD')
FROM 
    USED_GOODS_BOARD B 
INNER JOIN 
    USED_GOODS_REPLY R  
ON B.BOARD_ID = R.BOARD_ID;